name: TISC CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: make
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install valgrind

      - name: Enable permissions for test script
        run: chmod +x test.sh

      - name: Test project
        run: make test TESTARG="-v"
        
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install cppcheck splint clang-tidy clang-format

      - name: Run lint
        run: make lint
